### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/com.realm667.Wolfenstein_Blade_of_Agony#41]
@Talon1024 What do you think about adding a verification badge to the Flathub page?

```
Create a page at https://realm667.com/.well-known/org.flathub.VerifiedApps.txt containing the following token:
```

Cf. https://beta.flathub.org/apps/manage/com.realm667.Wolfenstein_Blade_of_Agony

**Comment by Talon1024** [comment]
I don't have the access rights to do that. I think the most I can do is edit the news articles and other content on the [BoA website](https://boa.realm667.com). @Tormentor667 is the administrator of [Realm667](https://www.realm667.com).

**Comment by Tormentor667** [comment]
Just uploaded the file, is everything set up right?

**Comment by Alexander-Wilms** [comment]
Now the badge is shown:

![image](https://user-images.githubusercontent.com/3226457/224958254-713d973d-4f48-456e-b17c-5ecf5b64b69c.png)
